config/routes.rb
# encoding: utf-8
#
# Redmine plugin for displaying announcements in the user interface
#
# originally publisehd by Sandeep Kumar / sandeepleo11
# migrated to Redmine 4.1 and enhanced by Stephan Wenzel
#
# Copyright © 2020 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#                  as far as not originally created by Sandeep Kumar
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

RedmineApp::Application.routes.draw do
  resources :projects do
    resources :announcements do
      collection do
        get 'hide'
      end
      member do
        get 'launch'
      end
    end
  end
  
  match '/announcements/preview', :to => 'announcements#preview', :as => 'preview_announcement', :via => [:get, :post, :put, :patch]
  resources :announcements do
    collection do
      get 'hide'
    end
    member do
      get 'launch'
    end
  end
  
end

app/controllers/announcements_controller.rb
# encoding: utf-8
#
# Redmine plugin for displaying announcements in the user interface
#
# originally publisehd by Sandeep Kumar / sandeepleo11
# migrated to Redmine 4.1 and enhanced by Stephan Wenzel
#
# Copyright © 2020 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#                  as far as not originally created by Sandeep Kumar
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

class AnnouncementsController < ApplicationController
  unloadable
  
  ########################################################################################
  #
  # helpers
  #
  ########################################################################################
  helper :announcement_routes
  include AnnouncementRoutesHelper
  
  ########################################################################################
  #
  # callbacks
  #
  ########################################################################################
  before_action :find_optional_project,              :except => [:hide] #does authorization check
  before_action :find_visible_announcement,          :only   => [:show]
  before_action :find_launchable_announcement,       :only   => [:launch]
  before_action :find_editable_announcement,         :only   => [:edit, :update]
  before_action :find_deletable_announcement,        :only   => [:destroy]
  before_action :set_timezone,                       :only   => [:new, :launch, :edit]
  
  ########################################################################################
  #
  # standard controller functions
  #
  ########################################################################################
  def index
    @announcements = Announcement.editable.where(:project => @project)
  end #def
  
  def show
  end #def
  
  def new
    @announcement = Announcement.new(:starts_at => Time.now, :ends_at => Time.now + 60.minutes)
  end #def
  
  def create
    @announcement = Announcement.new(announcement_params)
    if @announcement.save
      redirect_to _project_announcements_path(@project), :notice => l(:label_announcement_created)
    else
      flash[:error] = l(:label_announcement_not_created)
      render :action => "new"
    end
  end #def
  
  def edit
  end #def
  
  def update
    if @announcement.update_attributes(announcement_params)
      redirect_to _project_announcements_path(@project), :notice => l(:label_announcement_updated)
    else
      flash[:error] = l(:label_announcement_not_updated)
      render :action => "edit"
    end
  end #def
  
  def destroy
    @announcement.destroy
    redirect_to _project_announcements_path(@project)
  end #def
  
  ########################################################################################
  #
  # announcement specific functions
  #
  ########################################################################################
  def launch
    @announcement.update_attributes(:starts_at => Time.now, :ends_at => Time.now.end_of_day)
    redirect_to :back
  end #def 
  
  def hide
    session[:announcement_hide_time] = Time.now if User.current.logged?
    respond_to do |format|
      format.html { redirect_to :back }
      format.js
    end
  end #def
  
  def preview
    @announcement = Announcement.new(announcement_params)
    if Redmine::VERSION::MAJOR < 4
      @message = params.dig(:announcement, :message)
      render :layout => false
    else
      @previewed = @announcement
      @text = params.dig(:text)
      render :partial => 'preview'
    end
  end #def
  
  ########################################################################################
  #
  # private
  #
  ########################################################################################
  private
  
  def find_visible_announcement
    @announcement  = Announcement.visible.where(:id => params[:id]).first
    raise ActiveRecord::RecordNotFound unless @announcement
  rescue ActiveRecord::RecordNotFound
    render_404
  end #def
  
  def find_launchable_announcement
    @announcement  = Announcement.launchable.where(:id => params[:id]).first
    raise ActiveRecord::RecordNotFound unless @announcement
  rescue ActiveRecord::RecordNotFound
    render_404
  end #def
  
  def find_editable_announcement
    @announcement  = Announcement.editable.where(:id => params[:id]).first
    raise ActiveRecord::RecordNotFound unless @announcement
  rescue ActiveRecord::RecordNotFound
    render_404
  end #def
  
  def find_deletable_announcement
    @announcement  = Announcement.deletable.where(:id => params[:id]).first
    raise ActiveRecord::RecordNotFound unless @announcement
  rescue ActiveRecord::RecordNotFound
    render_404
  end #def
  
  def find_optional_visible_announcement
    @announcement  = Announcement.visible.where(:id => params[:id]).first
  end #def
  
  def find_optional_project
    @project = Project.find(params[:project_id]) unless params[:project_id].blank?
    allowed = User.current.allowed_to?({:controller => :announcements, :action => params[:action]}, @project, :global => false)
    allowed || User.current.admin? ? true : deny_access
  rescue ActiveRecord::RecordNotFound
    render_404
  end #def
  
  def set_timezone
    Time.zone = User.current.time_zone
  end #def
  
  def announcement_params
    params[:announcement] = params[:announcement].merge(:project_id => @project&.id, :author_id => User.current.id)
    params.require(:announcement).permit(:name, :message, :kind, :public, :starts_at, :ends_at, :project_id, :author_id) 
  end #def
end

app/views/announcements/_action_menu.html.erb
<%= content_tag :div, :class => "contextual" do -%>
  <%- if @announcement %>
    <%- if @announcement.new_record? %>
      <!-- no action menu items -->
    <%- else -%>
      <%- unless action_name == 'edit' %>
      <%= link_to(l(:button_edit), _edit_project_announcement_path(@project, @announcement), :class => 'icon icon-edit') %>
      <%- end %>
      <%= link_to(l(:button_delete),    _project_announcement_path(@project, @announcement), :class => 'icon icon-del', :confirm => l(:text_are_you_sure), :method => :delete ) %>
    <%- end %>
  <%- else %>
    <%= link_to(l(:label_new_announcement), _new_project_announcement_path(@project),        :class => "icon icon-add") %>
  <%- end %>
<% end -%>

app/views/announcements/_form.html.erb
<%= render_flash_messages %>
<%- flash.clear %>

<%= error_messages_for 'announcement' %>

<%= labelled_form_for @announcement, 
      { :url => _create_or_edit_project_announcement_path(@project, @announcement),
        :method => @announcement.new_record? ? :post : :put,
        :html => {:id => "announcement-form" }
      } do |f| %>
    
  <p>
    <%= f.text_field :name %>
  </p>
  
  <p>
    <%= f.text_area :message,
                   :cols => 60,
                   :rows => [[10, @announcement.message.to_s.length / 50].max, 20].min,
                   :accesskey => accesskey(:edit),
                   :class => 'wiki-edit',
                   :no_label => true %>
  </p>
  <%- if Redmine::VERSION::MAJOR < 4 %>
    <%= wikitoolbar_for 'announcement_message' %>
  <%- elsif @project %>
    <%= wikitoolbar_for 'announcement_message', preview_announcement_path(:project_id => @project.id, :id => @announcement.id) %>
  <%- else %>
    <%= wikitoolbar_for 'announcement_message' %>
  <%- end %>
  <p>
    <%= f.select :kind, Announcement.kinds_for_select %>
  </p>
  
  <p>
    <%= f.label :starts_at, l(:field_starts_at) %>
    <%= f.datetime_select :starts_at %>
  </p>
  
  <p>
    <%= f.label :ends_at, l(:field_ends_at) %>
    <%= f.datetime_select :ends_at %>
  </p>
  
  <p>
    <%= f.check_box :public, :disabled => (!User.current.admin? || !!@project) %>
  </p>
  
  <p class="button"><%= f.submit l(:button_submit) %></p>
  
  <%- if Redmine::VERSION::MAJOR < 4 %>
    <%= preview_link preview_announcement_path(:project_id => @project && @project.id, :id => @announcement.id), 'announcement-form' %>
  <%- end %>
  
<% end %>

<% heads_for_wiki_formatter %>

<div id="preview" class="wiki"></div>

app/views/announcements/_preview.html.erb
<% unless @text.blank? %>
  <%= textilizable @text, :object => @previewed %>
<% else	%>
  <p class="empty-preview"><%= l(:label_nothing_to_preview) %></p>
<% end %>

app/views/announcements/edit.html.erb
<%= render 'action_menu'-%>

<h2><%= @announcement.name %></h2>

<div class="box tabular">
  <%= render 'form' %>
</div>

app/views/announcements/hide_announcement.js.erb
$(document).ready(function(){
    $('#announcement').hide();
});	

app/views/announcements/index.html.erb
<%= render 'action_menu'-%>

<h2><%= l(:label_announcements) %></h2>

<table class="list">
  <thead>
  <tr>
    <th><%= l(:field_name) %></th>
    <th><%= l(:field_message) %></th>
    <th><%= l(:field_starts_at) %></th>
    <th><%= l(:field_ends_at) %></th>
  </tr>
  </thead>
  <tbody>
  <% @announcements.each do |announcement| %>
      <tr class='issue'>
        <td><%= link_to announcement.name, _edit_project_announcement_path(@project, announcement) %></td>
        <td><%= link_to announcement.message.strip[0..30], _edit_project_announcement_path(@project, announcement) %></td>
        <td><%= format_time(announcement.starts_at) %></td>
        <td><%= format_time(announcement.ends_at) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/announcements/new.html.erb
<h2><%= l(:label_new_announcement) %></h2>

<div class="box tabular">
  <div class="attributes">
    <%= render 'form' %>
  </div>
</div>

app/views/announcements/preview.html.erb
<% if @message %>
  <fieldset class="preview"><legend><%= l(:field_message) %></legend>
    <div class='<%= @announcement&.css_classes %>'>
      <%= textilizable @message, :object => @announcement %>
    </div>
  </fieldset>
<% end %>

app/views/announcements/show.html.erb
<%= render 'action_menu'-%>

<h2><%= @announcement.name %></h2>
<div class="box">
  <table class="attributes">
    <tbody>
    <tr>
      <th><%= l(:field_message) %></th>
      <td><%= @announcement.message %></td>
    </tr>
    <tr>
      <th><%= l(:field_starts_at) %></th>
      <td><%= format_time(@announcement.starts_at) %></td>
    </tr>
    <tr>
      <th><%= l(:field_ends_at) %></th>
      <td><%= format_time(@announcement.ends_at) %></td>
    </tr>
    </tbody>
  </table>
</div>