config/routes.rb
# encoding: utf-8
#
# Redmine plugin for displaying announcements in the user interface
#
# originally publisehd by Sandeep Kumar / sandeepleo11
# migrated to Redmine 4.1 and enhanced by Stephan Wenzel
#
# Copyright © 2020 Stephan Wenzel <stephan.wenzel@drwpatent.de>
#                  as far as not originally created by Sandeep Kumar
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#

RedmineApp::Application.routes.draw do
  resources :projects do
    resources :announcements do
      collection do
        get 'hide'
      end
      member do
        get 'launch'
      end
    end
  end
  
  match '/announcements/preview', :to => 'announcements#preview', :as => 'preview_announcement', :via => [:get, :post, :put, :patch]
  resources :announcements do
    collection do
      get 'hide'
    end
    member do
      get 'launch'
    end
  end
  
end

app/views/application/_announcements.html.erb
<%- if project.nil? || project.module_enabled?(:announcements) %>
  <% if current_announcements.any? %>
    <% for announcement in current_announcements %>
      <div id="announcementtop-<%= announcement.id %>" class='<%= announcement.css_classes %>'>
        <p><%= announcement.project&.name %></p>
        <p><%= h textilizable(announcement.message) %></p>
        <p><%= link_to l(:label_hide_announcements), hide_announcements_path if User.current.logged? %></p>
      </div>
      <%= javascript_tag "$(document).ready(function(){$('#content').prepend($('#announcementtop-#{announcement.id}'))});" %>
    <% end %>
    <% for announcement in current_announcements %>
      <div id="announcementbottom-<%= announcement.id %>" class='<%= announcement.css_classes %>'>
        <p><%= h announcement.project&.name %></p>
        <p><%= h textilizable(announcement.message) %></p>
        <p><%= link_to l(:label_hide_announcements), hide_announcements_path if User.current.logged? %></p>
      </div>
      <%= javascript_tag "$(document).ready(function(){$('#content').append($('#announcementbottom-#{announcement.id}'))});" %>
    <% end %>
  <%- end %>
<%- end %>